@extends('layout.template')

@section('content')
<table class="table table-striped">
    <th>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>NIM</th>
            <th>Kelas</th>
        </tr>
    </th>
    <tbody>
        <tr>
            <td>1</td>
            <td>Salsa</td>
            <td>520763</td>
            <td>A</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Nasywa</td>
            <td>514952</td>
            <td>A</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Nia</td>
            <td>516723</td>
            <td>A</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Jenni</td>
            <td></td>
            <td>A</td>
        </tr>
    </tbody>
</table>
@endsection

